const iconOptions = [
  { name: "Academic Cap", value: "academicCap"},
  { name: "Academy", value: "academy" },
  { name: "Address", value: "address" },
  { name: "Adjustments Horizontal", value: "adjustmentsHorizontal" },
  { name: "Airzone Logo", value: "airzoneLogo" },
  { name: "Arrow Down", value: "arrowDown" },
  { name: "Arrow Left", value: "arrowLeft" },
  { name: "Arrow Right", value: "arrowRight" },
  { name: "Arrow Right On Rectangle", value: "arrowRightOnRectangle" },
  { name: "Arrow Top Right On Square", value: "arrowTopRightOnSquare" },
  { name: "Arrow Up", value: "arrowUp" },
  { name: "Arrow Pointing Out", value: "arrowPointingOut" },
  { name: "Badge", value: "badge" },
  { name: "Briefcase", value: "briefcase" },
  { name: "Building", value: "building" },
  { name: "Camera", value: "camera" },
  { name: "Check", value: "check" },
  { name: "Check Circle", value: "checkCircle" },
  { name: "Clock", value: "clock"},
  { name: "Close", value: "close" },
  { name: "Close-Circle", value: "closeCircle" },
  { name: "Collapse", value: "collapse" },
  { name: "Credit Card", value: "creditCard" },
  { name: "Critical", value: "critical" },
  { name: "Currency Euro", value: "currencyEuro"},
  { name: "CursorArrowRays", value: "cursorArrowRays" },
  { name: "Delete", value: "delete" },
  { name: "Delivery Notes", value: "deliveryNotes" },
  { name: "Device Phone Mobile", value: "devicePhoneMobile" },
  { name: "Device Tablet", value: "deviceTablet" },
  { name: "Document", value: "document" },
  { name: "Dot", value: "dot" },
  { name: "Download", value: "download" },
  { name: "Download Cloud", value: "downloadCloud" },
  { name: "Ellipsis Horizontal", value: "ellipsisHorizontal" },
  { name: "Expand", value: "expand" },
  { name: "Expand Close", value: "expandClose" },
  { name: "Eye", value: "eye" },
  { name: "Faq", value: "faq" },
  { name: "Flashlight", value: "flashlight" },
  { name: "Folder", value: "folder" },
  { name: "Gears", value: "gears" },
  { name: "Hamburger", value: "hamburger" },
  { name: "Heart", value: "heart"},
  { name: "Home", value: "home" },
  { name: "Info", value: "info" },
  { name: "Info Solid", value: "infoSolid" },
  { name: "Invoices", value: "invoices" },
  { name: "InAirzone", value: "inAirzone" },
  { name: "Link", value: "link" },
  { name: "Minus", value: "minus" },
  { name: "Minus Circle", value: "minusCircle" },
  { name: "Orders", value: "orders" },
  { name: "Options", value: "options" },
  { name: "Pencil", value: "pencil" },
  { name: "Plus", value: "plus" },
  { name: "Printer", value: "printer" },
  { name: "Profile", value: "profile" },
  { name: "ProfileSolid", value: "profileSolid" },
  { name: "ProfilesDir", value: "profilesDir" },
  { name: "Password", value: "password" },
  { name: "PasswordHide", value: "passwordHide" },
  { name: "Persons", value: "persons" },
  { name: "Quotes", value: "quotes" },
  { name: "Rectangle Group", value: "rectangleGroup" },
  { name: "Returns", value: "returns" },
  { name: "Scan", value: "scan" },
  { name: "Search", value: "search" },
  { name: "Share", value: "share" },
  { name: "Spinner", value: "spinner" },
  { name: "Success", value: "success" },
  { name: "Support", value: "support" },
  { name: "Thumbs Down", value: "thumbsDown" },
  { name: "Thumbs Down Selected", value: "thumbsDownSelected" },
  { name: "Thumbs Up", value: "thumbsUp" },
  { name: "Thumbs Up Selected", value: "thumbsUpSelected" },
  { name: "Tickets", value: "tickets" },
  { name: "User", value: "user" },
  { name: "Users", value: "users" },
  { name: "Warning", value: "warning" },
  { name: "Warranties", value: "warranties" },
  { name: "Home", value: "home" },
  { name: "Dot", value: "dot" },
  { name: "Expand", value: "expand" },
  { name: "Collapse", value: "collapse" },
  { name: "Arrow Top Right On Square", value: "arrowTopRightOnSquare" },
  { name: "Gears", value: "gears" },
  { name: "Link", value: "link" },
  { name: "Faq", value: "faq" },
  { name: "Minus Circle", value: "minusCircle" },
  { name: "Share", value: "share" },
  { name: "WhatsApp", value: "whatsapp" },
  { name: "World", value: "world" },
  { name: "QrCode", value: "qrCode" },
]

module.exports = iconOptions